### ISSUE TITLE
Under which license can I use your code?

### ISSUE THREAD

**Issue by a-n-rose** [zhr1201/Multi-channel-speech-extraction-using-DNN#4]
Currently I do not see a license for this repository. According to GitHub’s Terms of Service, no one can use, distribute, modify or contribute back to this work unless an open source license is provided.

**Comment by zhr1201** [comment]
Thanks for the reminding, a license has been added.

**Comment by a-n-rose** [comment]
Thanks! Very interesting research btw. Thank you for making this open source.
